
name: Python package to PyPI
on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.2.1
        with:
          version: 1.1.4
          virtualenvs-create: false
          virtualenvs-in-project: false
      - name: publish to pypi
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --build
